"""create flags table

Revision ID: 33da11c2fc1c
Revises: 6401dfc3378a
Create Date: 2017-04-12 12:07:02.615275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33da11c2fc1c'
down_revision = '6401dfc3378a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flags')
    # ### end Alembic commands ###
