"""Memories

Revision ID: d2c39b30bc86
Revises: df110a4504d7
Create Date: 2017-12-06 18:54:49.649424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c39b30bc86'
down_revision = 'df110a4504d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('is_memory', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'is_memory')
    # ### end Alembic commands ###
