"""adding media type to story table

Revision ID: 63d6039354d3
Revises: 33da11c2fc1c
Create Date: 2017-04-17 17:44:10.912952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d6039354d3'
down_revision = '33da11c2fc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('media_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'media_type')
    # ### end Alembic commands ###
