"""Add timestamp to group creation

Revision ID: 382fd2510203
Revises: 4a7d101617ae
Create Date: 2017-12-27 23:31:32.803819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382fd2510203'
down_revision = '4a7d101617ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'timestamp')
    # ### end Alembic commands ###
