"""adding media type to story

Revision ID: 22ade4399541
Revises: e980d5636c63
Create Date: 2017-04-18 16:09:05.880888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ade4399541'
down_revision = 'e980d5636c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('media_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'media_type')
    # ### end Alembic commands ###
