"""Indexes and memories

Revision ID: 3b22ec731793
Revises: 8cabf7921838
Create Date: 2017-12-06 19:06:13.044223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b22ec731793'
down_revision = '8cabf7921838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blocks_blocker_id'), 'blocks', ['blocker_id'], unique=False)
    op.drop_index('idx_blocks_blocker_id', table_name='blocks')
    op.create_index(op.f('ix_comments_story_id'), 'comments', ['story_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_index('idx_comments_story_id', table_name='comments')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.drop_index('idx_devices_user_id', table_name='devices')
    op.create_index(op.f('ix_memberships_group_id'), 'memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.drop_index('idx_memberships_group_id', table_name='memberships')
    op.drop_index('idx_memberships_user_id', table_name='memberships')
    op.add_column('stories', sa.Column('is_memory', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_stories_group_id'), 'stories', ['group_id'], unique=False)
    op.create_index(op.f('ix_stories_timestamp'), 'stories', ['timestamp'], unique=False)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.drop_index('idx_stories_group_id', table_name='stories')
    op.drop_index('idx_stories_timestamp', table_name='stories')
    op.drop_index('idx_stories_user_id', table_name='stories')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('idx_users_username', table_name='users')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('idx_stories_user_id', 'stories', ['user_id'], unique=False)
    op.create_index('idx_stories_timestamp', 'stories', ['timestamp'], unique=False)
    op.create_index('idx_stories_group_id', 'stories', ['group_id'], unique=False)
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_timestamp'), table_name='stories')
    op.drop_index(op.f('ix_stories_group_id'), table_name='stories')
    op.drop_column('stories', 'is_memory')
    op.create_index('idx_memberships_user_id', 'memberships', ['user_id'], unique=False)
    op.create_index('idx_memberships_group_id', 'memberships', ['group_id'], unique=False)
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_group_id'), table_name='memberships')
    op.create_index('idx_devices_user_id', 'devices', ['user_id'], unique=False)
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('idx_comments_story_id', 'comments', ['story_id'], unique=False)
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_story_id'), table_name='comments')
    op.create_index('idx_blocks_blocker_id', 'blocks', ['blocker_id'], unique=False)
    op.drop_index(op.f('ix_blocks_blocker_id'), table_name='blocks')
    # ### end Alembic commands ###
