"""Add timestamp to group creation

Revision ID: a558b84ba9a3
Revises: 3b22ec731793
Create Date: 2017-12-27 23:33:52.472415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a558b84ba9a3'
down_revision = '3b22ec731793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'timestamp')
    # ### end Alembic commands ###
